image:
  file: .gitpod.Dockerfile
tasks:
  - init:
      cabal run
vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
    - dracula-theme.theme-dracula
    - vscode-icons-team.vscode-icons